### ISSUE TITLE
Error when using Dig to annotate the mutation bed file

### ISSUE THREAD

**Issue by virdzek-g** [maxwellsh/DIGDriver#7]
Hello,

I am getting an error when using Dig to annotate the mutation bed file created in step 1. Could you please help me find out what's wrong, please?

Best regards,
Gabriela

`DigPreprocess.py annotMutationFile ./input.bed ./reference_hg19_Homo_sapiens_assembly19.fasta output`

Adding mutation function
dyld[49721]: Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: <34EA1D6C-7BD3-38A2-9869-5FCB9627BA35> /Users/gv9/opt/anaconda3/envs/digdriver/lib/R/lib/libRblas.dylib
  Reason: tried: '/Users/gv9/opt/anaconda3/envs/digdriver/lib/R/lib/libgfortran.3.dylib' (no such file), '/Users/gv9/opt/anaconda3/envs/digdriver/lib/R/lib/../../libgfortran.3.dylib' (no such file), '/Users/gv9/opt/anaconda3/envs/digdriver/lib/libgfortran.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/gv9/opt/anaconda3/envs/digdriver/lib/libgfortran.3.dylib' (no such file), '/Users/gv9/opt/anaconda3/envs/digdriver/lib/R/lib/../../libgfortran.3.dylib' (no such file), '/Users/gv9/opt/anaconda3/envs/digdriver/lib/libgfortran.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/gv9/opt/anaconda3/envs/digdriver/lib/libgfortran.3.dylib' (no such file), '/opt/conda/conda-bld/r-base_1536076838216/work/lib/libgfortran.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/conda/conda-bld/r-base_1536076838216/work/lib/libgfortran.3.dylib' (no such file), '/Users/gv9/opt/anaconda3/envs/digdriver/lib/libgfortran.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/gv9/opt/anaconda3/envs/digdriver/lib/libgfortran.3.dylib' (no such file), '/Users/gv9/opt/anaconda3/envs/digdriver/lib/R/bin/exec/../../../libgfortran.3.dylib' (no such file), '/Users/gv9/opt/anaconda3/envs/digdriver/lib/libgfortran.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/gv9/opt/anaconda3/envs/digdriver/lib/libgfortran.3.dylib' (no such file), '/opt/conda/conda-bld/r-base_1536076838216/work/lib/libgfortran.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/conda/conda-bld/r-base_1536076838216/work/lib/libgfortran.3.dylib' (no such file), '/Users/gv9/opt/anaconda3/envs/digdriver/lib/libgfortran.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/gv9/opt/anaconda3/envs/digdriver/lib/libgfortran.3.dylib' (no such file), '/Users/gv9/opt/anaconda3/envs/digdriver/lib/R/bin/exec/../../../libgfortran.3.dylib' (no such file), '/Users/gv9/opt/anaconda3/envs/digdriver/lib/R/lib/libgfortran.3.dylib' (no such file), '/Users/gv9/opt/anaconda3/envs/digdriver/lib/libgfortran.3.dylib' (no such file)
Adding mutation context
Reading in mutation file
Traceback (most recent call last):
  File "/Users/gv9/opt/anaconda3/envs/digdriver/bin/DigPreprocess.py", line 366, in <module>
    args.func(args)
  File "/Users/gv9/opt/anaconda3/envs/digdriver/bin/DigPreprocess.py", line 117, in annotMutationFile
    addMutationContext(args)
  File "/Users/gv9/opt/anaconda3/envs/digdriver/bin/DigPreprocess.py", line 82, in addMutationContext
    df_mut = mutation_tools.read_mutation_file(args.fmut, drop_duplicates=False)
  File "/Users/gv9/opt/anaconda3/envs/digdriver/lib/python3.7/site-packages/DIGDriver/data_tools/mutation_tools.py", line 48, in read_mutation_file
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output.h5'

**Comment by Gengchao-WANG** [comment]
Have you solved the problem? I had no problem the first time I ran this program. However, when I re-installed conda and digdriver, I got this error and couldn't fix it.
